/*
 * core_variant.c
 *
 * Created: 9/27/2020 11:00:33 AM
 *  Author: Kirill
 */ 

#include "core_variant.h"

const Flexcom *FLEXCOMS[FLEXCOM_INST_NUM] = FLEXCOM_INSTS;

const uint8_t FLEXCOM_IDS[FLEXCOM_INST_NUM] = {
	#if (SAM4S_SERIES || SAM4E_SERIES)
		ID_FLEXCOM0, ID_FLEXCOM1
	#elif SAM3XA_SERIES
		ID_FLEXCOM0, ID_FLEXCOM1, ID_FLEXCOM2
	#elif SAME70_SERIES
		ID_FLEXCOM0, ID_FLEXCOM1, ID_FLEXCOM2, ID_FLEXCOM3, ID_FLEXCOM4
	#elif __SAMG55J19__
		ID_FLEXCOM0, ID_FLEXCOM1, ID_FLEXCOM2, ID_FLEXCOM3, ID_FLEXCOM4, ID_FLEXCOM5, ID_FLEXCOM6, ID_FLEXCOM7
	#elif SAMG55_SERIES
		ID_FLEXCOM0, ID_FLEXCOM1, ID_FLEXCOM2, ID_FLEXCOM3, ID_FLEXCOM4, ID_FLEXCOM5, ID_FLEXCOM6
	#endif
};

const IRQn_Type FLEXCOM_IRQNS[FLEXCOM_INST_NUM] = {
    #if (SAM4S_SERIES || SAM4E_SERIES)
    FLEXCOM0_IRQn, FLEXCOM1_IRQn
    #elif SAM3XA_SERIES
    FLEXCOM0_IRQn, FLEXCOM1_IRQn, FLEXCOM2_IRQn
    #elif SAME70_SERIES
    FLEXCOM0_IRQn, FLEXCOM1_IRQn, FLEXCOM2_IRQn, FLEXCOM3_IRQn, FLEXCOM4_IRQn
    #elif __SAMG55J19__
    FLEXCOM0_IRQn, FLEXCOM1_IRQn, FLEXCOM2_IRQn, FLEXCOM3_IRQn, FLEXCOM4_IRQn, FLEXCOM5_IRQn, FLEXCOM6_IRQn, FLEXCOM7_IRQn
    #elif SAMG55_SERIES
    FLEXCOM0_IRQn, FLEXCOM1_IRQn, FLEXCOM2_IRQn, FLEXCOM3_IRQn, FLEXCOM4_IRQn, FLEXCOM5_IRQn, FLEXCOM6_IRQn
    #endif
};
